// Code generated by goctl. DO NOT EDIT.
package types

type DetailResp struct {
	UserInfo User `json:"userInfo"`
}

type JwtAccess struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	JwtAccess JwtAccess `json:"jwtAccess"`
}

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	JwtAccess JwtAccess `json:"jwtAccess"`
}

type UpdateUserInfoReq struct {
	Sex   int64  `json:"sex"`
	Email string `json:"email"`
	Sign  string `json:"sign"`
}

type User struct {
	Username    string  `json:"username"`
	Password    string  `json:"password"`
	Money       float64 `json:"money"`
	Sex         int64   `json:"sex"`
	PhoneNumber int64   `json:"phoneNumber"`
	Email       string  `json:"email"`
	Sign        string  `json:"sign"`
}
