// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"GoBao/server/order/rpc/internal/logic"
	"GoBao/server/order/rpc/internal/svc"
	"GoBao/server/order/rpc/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) CreateSeckillOrder(ctx context.Context, in *pb.CreateSeckillOrderReq) (*pb.CreateSeckillOrderResp, error) {
	l := logic.NewCreateSeckillOrderLogic(ctx, s.svcCtx)
	return l.CreateSeckillOrder(in)
}

func (s *OrderServer) GetOrderList(ctx context.Context, in *pb.GetOrderListReq) (*pb.GetOrderListResp, error) {
	l := logic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}

func (s *OrderServer) GetOrderDetail(ctx context.Context, in *pb.GetOrderDetailReq) (*pb.GetOrderDetailResp, error) {
	l := logic.NewGetOrderDetailLogic(ctx, s.svcCtx)
	return l.GetOrderDetail(in)
}

func (s *OrderServer) DeleteOrder(ctx context.Context, in *pb.DeleteOrderReq) (*pb.DeleteOrderResp, error) {
	l := logic.NewDeleteOrderLogic(ctx, s.svcCtx)
	return l.DeleteOrder(in)
}

func (s *OrderServer) UpdateOrderStatus(ctx context.Context, in *pb.UpdateOrderStatusReq) (*pb.UpdateOrderStatusResp, error) {
	l := logic.NewUpdateOrderStatusLogic(ctx, s.svcCtx)
	return l.UpdateOrderStatus(in)
}
