// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	pay "GoBao/server/pay/api/internal/handler/pay"
	"GoBao/server/pay/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/pay",
				Handler: pay.OrderPayHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/pay/v1"),
	)
}
