// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: cart.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Cart_AddProductToCart_FullMethodName        = "/cart.cart/AddProductToCart"
	Cart_DeleteProductFromCart_FullMethodName   = "/cart.cart/DeleteProductFromCart"
	Cart_UpdateCartProductDetail_FullMethodName = "/cart.cart/UpdateCartProductDetail"
	Cart_GetCartList_FullMethodName             = "/cart.cart/GetCartList"
)

// CartClient is the client API for Cart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CartClient interface {
	AddProductToCart(ctx context.Context, in *AddProductToCartRequest, opts ...grpc.CallOption) (*AddProductToCartResponse, error)
	DeleteProductFromCart(ctx context.Context, in *DeleteProductFromCartRequest, opts ...grpc.CallOption) (*DeleteProductFromCartResponse, error)
	UpdateCartProductDetail(ctx context.Context, in *UpdateCartProductDetailRequest, opts ...grpc.CallOption) (*UpdateCartProductDetailResponse, error)
	GetCartList(ctx context.Context, in *GetCartListRequest, opts ...grpc.CallOption) (*GetCartListResponse, error)
}

type cartClient struct {
	cc grpc.ClientConnInterface
}

func NewCartClient(cc grpc.ClientConnInterface) CartClient {
	return &cartClient{cc}
}

func (c *cartClient) AddProductToCart(ctx context.Context, in *AddProductToCartRequest, opts ...grpc.CallOption) (*AddProductToCartResponse, error) {
	out := new(AddProductToCartResponse)
	err := c.cc.Invoke(ctx, Cart_AddProductToCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) DeleteProductFromCart(ctx context.Context, in *DeleteProductFromCartRequest, opts ...grpc.CallOption) (*DeleteProductFromCartResponse, error) {
	out := new(DeleteProductFromCartResponse)
	err := c.cc.Invoke(ctx, Cart_DeleteProductFromCart_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) UpdateCartProductDetail(ctx context.Context, in *UpdateCartProductDetailRequest, opts ...grpc.CallOption) (*UpdateCartProductDetailResponse, error) {
	out := new(UpdateCartProductDetailResponse)
	err := c.cc.Invoke(ctx, Cart_UpdateCartProductDetail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cartClient) GetCartList(ctx context.Context, in *GetCartListRequest, opts ...grpc.CallOption) (*GetCartListResponse, error) {
	out := new(GetCartListResponse)
	err := c.cc.Invoke(ctx, Cart_GetCartList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CartServer is the server API for Cart service.
// All implementations must embed UnimplementedCartServer
// for forward compatibility
type CartServer interface {
	AddProductToCart(context.Context, *AddProductToCartRequest) (*AddProductToCartResponse, error)
	DeleteProductFromCart(context.Context, *DeleteProductFromCartRequest) (*DeleteProductFromCartResponse, error)
	UpdateCartProductDetail(context.Context, *UpdateCartProductDetailRequest) (*UpdateCartProductDetailResponse, error)
	GetCartList(context.Context, *GetCartListRequest) (*GetCartListResponse, error)
	mustEmbedUnimplementedCartServer()
}

// UnimplementedCartServer must be embedded to have forward compatible implementations.
type UnimplementedCartServer struct {
}

func (UnimplementedCartServer) AddProductToCart(context.Context, *AddProductToCartRequest) (*AddProductToCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProductToCart not implemented")
}
func (UnimplementedCartServer) DeleteProductFromCart(context.Context, *DeleteProductFromCartRequest) (*DeleteProductFromCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProductFromCart not implemented")
}
func (UnimplementedCartServer) UpdateCartProductDetail(context.Context, *UpdateCartProductDetailRequest) (*UpdateCartProductDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCartProductDetail not implemented")
}
func (UnimplementedCartServer) GetCartList(context.Context, *GetCartListRequest) (*GetCartListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCartList not implemented")
}
func (UnimplementedCartServer) mustEmbedUnimplementedCartServer() {}

// UnsafeCartServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CartServer will
// result in compilation errors.
type UnsafeCartServer interface {
	mustEmbedUnimplementedCartServer()
}

func RegisterCartServer(s grpc.ServiceRegistrar, srv CartServer) {
	s.RegisterService(&Cart_ServiceDesc, srv)
}

func _Cart_AddProductToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).AddProductToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_AddProductToCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).AddProductToCart(ctx, req.(*AddProductToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_DeleteProductFromCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductFromCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).DeleteProductFromCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_DeleteProductFromCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).DeleteProductFromCart(ctx, req.(*DeleteProductFromCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_UpdateCartProductDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartProductDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).UpdateCartProductDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_UpdateCartProductDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).UpdateCartProductDetail(ctx, req.(*UpdateCartProductDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cart_GetCartList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCartListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CartServer).GetCartList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Cart_GetCartList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CartServer).GetCartList(ctx, req.(*GetCartListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Cart_ServiceDesc is the grpc.ServiceDesc for Cart service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cart_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cart.cart",
	HandlerType: (*CartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddProductToCart",
			Handler:    _Cart_AddProductToCart_Handler,
		},
		{
			MethodName: "DeleteProductFromCart",
			Handler:    _Cart_DeleteProductFromCart_Handler,
		},
		{
			MethodName: "UpdateCartProductDetail",
			Handler:    _Cart_UpdateCartProductDetail_Handler,
		},
		{
			MethodName: "GetCartList",
			Handler:    _Cart_GetCartList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cart.proto",
}
