Name: product
Host: 0.0.0.0
Port: 1002

# JWT配置
JwtAuth:
  AccessSecret: gobaoAccessSecret
  AccessExpire: 604800    # 7天的过期时间，1天为86400


# log配置
Log:
  ServiceName: product-api
  Level: error

ProductRpcConf:
  EndPoints:
    - 127.0.0.1:2002

UserRpcConf:
  EndPoints:
    - 127.0.0.1:2001
  NonBlock: true