// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package cart

import (
	"context"

	"GoBao/server/cart/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddProductToCartRequest         = pb.AddProductToCartRequest
	AddProductToCartResponse        = pb.AddProductToCartResponse
	CartProduct                     = pb.CartProduct
	DeleteProductFromCartRequest    = pb.DeleteProductFromCartRequest
	DeleteProductFromCartResponse   = pb.DeleteProductFromCartResponse
	GetCartListRequest              = pb.GetCartListRequest
	GetCartListResponse             = pb.GetCartListResponse
	UpdateCartProductDetailRequest  = pb.UpdateCartProductDetailRequest
	UpdateCartProductDetailResponse = pb.UpdateCartProductDetailResponse

	Cart interface {
		AddProductToCart(ctx context.Context, in *AddProductToCartRequest, opts ...grpc.CallOption) (*AddProductToCartResponse, error)
		DeleteProductFromCart(ctx context.Context, in *DeleteProductFromCartRequest, opts ...grpc.CallOption) (*DeleteProductFromCartResponse, error)
		UpdateCartProductDetail(ctx context.Context, in *UpdateCartProductDetailRequest, opts ...grpc.CallOption) (*UpdateCartProductDetailResponse, error)
		GetCartList(ctx context.Context, in *GetCartListRequest, opts ...grpc.CallOption) (*GetCartListResponse, error)
	}

	defaultCart struct {
		cli zrpc.Client
	}
)

func NewCart(cli zrpc.Client) Cart {
	return &defaultCart{
		cli: cli,
	}
}

func (m *defaultCart) AddProductToCart(ctx context.Context, in *AddProductToCartRequest, opts ...grpc.CallOption) (*AddProductToCartResponse, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.AddProductToCart(ctx, in, opts...)
}

func (m *defaultCart) DeleteProductFromCart(ctx context.Context, in *DeleteProductFromCartRequest, opts ...grpc.CallOption) (*DeleteProductFromCartResponse, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.DeleteProductFromCart(ctx, in, opts...)
}

func (m *defaultCart) UpdateCartProductDetail(ctx context.Context, in *UpdateCartProductDetailRequest, opts ...grpc.CallOption) (*UpdateCartProductDetailResponse, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.UpdateCartProductDetail(ctx, in, opts...)
}

func (m *defaultCart) GetCartList(ctx context.Context, in *GetCartListRequest, opts ...grpc.CallOption) (*GetCartListResponse, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.GetCartList(ctx, in, opts...)
}
