// Code generated by goctl. DO NOT EDIT.
package types

type BasePage struct {
	Page int64 `json:"page"`
	Size int64 `json:"size"`
}

type CreateProductReq struct {
	Name   string  `json:"name"`
	Price  float64 `json:"price"`
	Stock  int64   `json:"stock"`
	UserID int64   `json:"userId"`
}

type DeleteProductReq struct {
	ProductIDs []int64 `json:"productIDs"`
}

type GetSeckillDetailReq struct {
	SeckillID int64 `json:"seckillId"`
}

type GetSeckillDetailResp struct {
	SeckillProduct
}

type GetSeckillListReq struct {
	StartTime string `json:"startTime"`
	Time      int64  `json:"time"`
}

type GetSeckillListResp struct {
	SeckillProducts []SmallSeckill `json:"seckillProducts"`
}

type Product struct {
	ID         int64   `json:"id"`
	Name       string  `json:"name"`
	Price      float64 `json:"price"`
	Stock      int64   `json:"stock"`
	Status     int64   `json:"status"`
	CreateTime int64   `json:"createTime"`
	UpdateTime int64   `json:"updateTime"`
}

type ProductDetailReq struct {
	ProductID int64 `json:"productId"`
}

type ProductDetailResp struct {
	Product Product `json:"product"`
}

type RecommendProductResp struct {
	Products []SmallProduct `json:"products"`
}

type SearchProductReq struct {
	Keyword string `json:"keyword"`
	Sort    string `json:"sort"`
	OnSale  int64  `json:"onSale"`
	BasePage
}

type SearchProductResp struct {
	Products []SmallProduct `json:"products"`
}

type SeckillProduct struct {
	Product
	SeckillPrice float64 `json:"seckillPrice"`
	StockCount   int64   `json:"stockCount"`
	StartTime    string  `json:"startTime"`
	Time         int64   `json:"time"`
}

type SmallProduct struct {
	ID            int64   `json:"id"`
	Name          string  `json:"name"`
	Price         float64 `json:"price"`
	DiscountPrice float64 `json:"discountPrice"`
}

type SmallSeckill struct {
	SeckillID    int64   `json:"seckillId"`
	Name         string  `json:"name"`
	SeckillPrice float64 `json:"seckillPrice"`
}
