// Code generated by goctl. DO NOT EDIT.
// Source: pay.proto

package server

import (
	"context"

	"GoBao/server/pay/rpc/internal/logic"
	"GoBao/server/pay/rpc/internal/svc"
	"GoBao/server/pay/rpc/pb"
)

type PayServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPayServer
}

func NewPayServer(svcCtx *svc.ServiceContext) *PayServer {
	return &PayServer{
		svcCtx: svcCtx,
	}
}

func (s *PayServer) OrderPayment(ctx context.Context, in *pb.OrderPaymentReq) (*pb.OrderPaymentResp, error) {
	l := logic.NewOrderPaymentLogic(ctx, s.svcCtx)
	return l.OrderPayment(in)
}

func (s *PayServer) GetPaymentDetail(ctx context.Context, in *pb.GetPaymentDetailReq) (*pb.GetPaymentDetailResp, error) {
	l := logic.NewGetPaymentDetailLogic(ctx, s.svcCtx)
	return l.GetPaymentDetail(in)
}
