global:
  scrape_interval: 15s # 默认抓取间隔
  evaluation_interval: 15s # 默认规则评估间隔

scrape_configs:
  - job_name: 'gobao'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'user-api'
    static_configs:
      - targets:
          - 127.0.0.1:1001
  - job_name: 'user-rpc'
    static_configs:
      - targets:
          - 127.0.0.1:2001