// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	cart "GoBao/server/cart/api/internal/handler/cart"
	"GoBao/server/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/cart",
				Handler: cart.AddProductToCartHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/cart",
				Handler: cart.DeleteProductFromCartHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/cart",
				Handler: cart.UpdateCartProductDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/cart",
				Handler: cart.GetCartListHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/cart/v1"),
	)
}
